swagger: "2.0"
info:
  description: "Endpoint definitions of this template project"
  version: "1.0.0"
  title: "Template Project"
basePath: "/api/v1"
schemes:
  - "https"
paths:
  /users:
    post:
      summary: "Save a new user"
      parameters:
        - in: "body"
          name: "SaveUserDto"
          required: true
          schema:
            $ref: '#/definitions/SaveUserDto'
      responses:
        201:
          description: "Created"
          schema:
            $ref: '#/definitions/GetUserDto'
        default:
          description: "Unexpected Error"
          schema:
            $ref: '#/definitions/Error'

  /users/{id}:
    get:
      summary: "Get a user by id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: '#/definitions/GetUserDto'
        default:
          description: "Unexpected Error"
          schema:
            $ref: '#/definitions/Error'

  /items:
    get:
      summary: "Get All items"
      parameters:
        - in: "query"
          name: "userId"
          type: "string"
        - in: "query"
          name: "name"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: '#/definitions/GetItemsDto'
        default:
          description: "Unexpected Error"
          schema:
            $ref: '#/definitions/Error'

    post:
      summary: "Save a new item"
      parameters:
        - in: "body"
          name: "SaveItemDto"
          required: true
          schema:
            $ref: '#/definitions/SaveItemDto'
      responses:
        201:
          description: "Created"
          schema:
            $ref: '#/definitions/GetItemDto'
        default:
          description: "Unexpected Error"
          schema:
            $ref: '#/definitions/Error'

  /items/{id}:
    get:
      summary: "Get an item by id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: '#/definitions/GetItemDto'
        default:
          description: "Unexpected Error"
          schema:
            $ref: '#/definitions/Error'


definitions:
  SaveUserDto:
    type: "object"
    required:
      - "name"
    properties:
      name:
        type: "string"

  GetUserDto:
    required:
      - "user"
    properties:
      user:
        $ref: '#/definitions/User'

  User:
    type: "object"
    required:
      - "id"
      - "name"
      - "items"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      items:
        type: "array"
          items:
          $ref: '#/definitions/Item'

  SaveItemDto:
    type: "object"
    required:
      - "userId"
      - "name"
    properties:
      userId:
        type: "string"
      name:
        type: "string"

  GetItemsDto:
    required:
      - items
    properties:
      items:
        type: "array"
        items:
          $ref: '#/definitions/Item'

  GetItemDto:
    required:
      - item
    properties:
      item:
        $ref: '#/definitions/Item'

  Item:
    type: "object"
    required:
      - "id"
      - "userId"
      - "name"
    properties:
      id:
        type: "string"
      userId:
        type: "string"
      name:
        type: "string"

  Error:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
